<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IceCrow.Battlegrounds\IceCrow.Battlegrounds.csproj" />
    <ProjectReference Include="..\IceCrow.Battlegrounds.Memory\IceCrow.Battlegrounds.Memory.csproj" />
    <ProjectReference Include="..\IceCrow.Hearthstone.Entities\IceCrow.Hearthstone.Entities.csproj" />
    <ProjectReference Include="..\IceCrow.Hearthstone.Protocol\IceCrow.Hearthstone.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
