<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IceCrow.Live\IceCrow.Live.csproj" />
    <ProjectReference Include="..\..\src\IceCrow.Recording\IceCrow.Recording.csproj" />
  </ItemGroup>

</Project>
